# frozen_string_literal: true

# Steep configuration for the `assistant` gem (docs/v1 M8).
#
# A single `:lib` target type-checks the gem's Ruby code against the
# sibling `lib/**/*.rbs` declarations.
#
# Steep is intentionally restricted to files that do **not** rely on
# metaprogramming Steep cannot model:
#
#   * `Module#define_method` (used by InputBuilder to install the
#     per-input `valid_type_*?`, `valid_required_*?`, etc. methods);
#   * `Kernel#send` to one of those generated methods;
#   * Ruby refinements (`Assistant::Refinements::StringBlankness`);
#   * cross-module helper lookups that only resolve once every
#     `InputBuilder` submodule has been mixed into the same singleton.
#
# Signatures for the excluded files still live in `lib/**/*.rbs` so
# downstream consumers (and the included files) can name the modules
# and call the helpers. The full per-input surface generated by
# `Service.input` is the subject of M11 (`bin/assistant-rbs`).
target :lib do
  signature 'lib'

  library 'fileutils'
  library 'optparse'

  check 'lib/assistant.rb'
  check 'lib/assistant/version.rb'
  check 'lib/assistant/input_builder.rb'
  check 'lib/assistant/input_builder/registry.rb'
  check 'lib/assistant/input_builder/default_option.rb'
  check 'lib/assistant/input_builder/optional_option.rb'
  check 'lib/assistant/rbs_generator.rb'
  check 'lib/assistant/rbs_generator/renderer.rb'
  check 'lib/assistant/rbs_generator/writer.rb'
  check 'lib/assistant/rbs_generator/cli.rb'
end

# Type-checks the sample service in `examples/greeter.rb` against the
# .rbs generated by `exe/assistant-rbs` and shipped in `sig/examples/`.
# Doubles as the M11 regression that the generator's output is in fact
# accepted by Steep.
#
# The check is scoped to `greeter.rb` rather than the whole `examples/`
# tree because the P6-P12 example folders (docs/v1/08-github-pages.md)
# are documentation companions, not Steep regressions: hand-writing
# `.rbs` sidecars for every Service / POJO they ship would be cost
# without leverage. The `rbs_generator` example (P12) re-includes its
# own files via a dedicated check below.
target :examples do
  signature 'lib'
  signature 'sig'

  check 'examples/greeter.rb'
end
