# frozen_string_literal: true

require 'fileutils'
require 'optparse'

# Per-class RBS generator for `Assistant::Service` subclasses. The
# generic RBS shipped in `lib/assistant/service.rbs` cannot describe the
# per-input getter / predicate methods produced by the
# `Assistant::InputBuilder` DSL because their names and return types are
# only known at class-definition time. Users with Steep run this
# generator over their service files to obtain accurate signatures for
# their own subclasses.
#
# The generator is intentionally **not** loaded by `require 'assistant'`
# -- it is a developer-time tool. The shipped `exe/assistant-rbs`
# binary requires it explicitly.
#
# Marked Experimental in `docs/v1/01-api-surface.md` so the output
# format may evolve within 1.x.
#
# See `docs/v1/02-features.md` (M11) for the contract.
module Assistant::RbsGenerator
  MARKER = '# Generated by assistant-rbs; do not edit.'
  DEFAULT_OUTPUT_DIR = 'sig'
  DEFAULT_INPUT_PATHS = ['lib'].freeze

  # Converts a Service subclass to a `.rbs` source string. Pure
  # function; does no I/O.
  module Renderer
    class << self
      def render(service_class)
        name = service_class.name or raise 'anonymous Service class cannot be rendered'
        segments = name.split('::')
        # `String#split` on a non-empty string always returns at least
        # one element, but Steep can't prove that -- guard for narrowing.
        class_name = segments.pop or raise "unexpected empty name for #{service_class.inspect}"
        body_lines = render_class_body(class_name, service_class.input_definitions)
        nested_lines = nest_in_modules(segments, body_lines)
        "#{[MARKER, '', *nested_lines].join("\n")}\n"
      end

      private

      def render_class_body(class_name, definitions)
        header = "class #{class_name} < Assistant::Service"
        method_lines = definitions.flat_map { |name, options| input_method_lines(name, options) }
        return [header, 'end'] if method_lines.empty?

        [header, '', *method_lines.map { |line| "  #{line}" }, '', 'end']
      end

      def nest_in_modules(segments, body_lines)
        segments.reverse.reduce(body_lines) do |body, segment|
          indented = body.map { |line| line.empty? ? '' : "  #{line}" }
          ["module #{segment}", *indented, 'end']
        end
      end

      def input_method_lines(name, options)
        [
          "def #{name}: () -> #{render_type(name, options)}",
          "def #{name}?: () -> bool"
        ]
      end

      def render_type(name, options)
        raise "input #{name.inspect} has no `type:` declared" unless options.key?(:type)

        rendered = Array(options[:type]).map { |type| render_single_type(name, type) }
        union = rendered.length == 1 ? rendered.first : "(#{rendered.join(' | ')})"
        options[:allow_nil] == true ? "#{union}?" : union
      end

      def render_single_type(name, type)
        raise "input #{name.inspect} has non-Class type #{type.inspect}" unless type.is_a?(Module)

        type.name || raise("input #{name.inspect} has anonymous type")
      end
    end
  end

  # File-writing layer with marker-aware idempotency.
  class Writer
    def initialize(output_dir:, quiet: false, stdout: $stdout, stderr: $stderr)
      @output_dir = output_dir
      @quiet = quiet
      @stdout = stdout
      @stderr = stderr
    end

    # Returns one of :written, :unchanged, :skipped.
    def write(service_class, contents)
      target = path_for(service_class)
      return skip!(target) if exists_without_marker?(target)
      return unchanged!(target) if File.exist?(target) && File.read(target) == contents

      FileUtils.mkdir_p(File.dirname(target))
      File.write(target, contents)
      announce("[written]   #{target}")
      :written
    end

    private

    attr_reader :output_dir, :quiet, :stdout, :stderr

    def exists_without_marker?(target)
      File.exist?(target) && !generated_file?(target)
    end

    def skip!(target)
      stderr.puts "[skipped]   #{target} (no generator marker; will not overwrite)"
      :skipped
    end

    def unchanged!(target)
      announce("[unchanged] #{target}")
      :unchanged
    end

    def path_for(service_class)
      name = service_class.name or raise "anonymous Service class #{service_class.inspect}"
      relative = name.split('::').map { |seg| underscore(seg) }.join('/')
      File.join(output_dir, "#{relative}.rbs")
    end

    # ASCII-only underscoring -- the gem ships no runtime deps, so this
    # mirrors the common ActiveSupport rule without pulling it in.
    def underscore(camel)
      camel.gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2').gsub(/([a-z\d])([A-Z])/, '\1_\2').downcase
    end

    def generated_file?(path)
      File.foreach(path).first&.chomp == MARKER
    end

    def announce(message)
      stdout.puts(message) unless quiet
    end
  end

  # Command-line entry point. Parses argv, loads the input files,
  # discovers Service subclasses, renders, writes.
  class Cli
    USAGE = <<~USAGE
      Usage: assistant-rbs [PATH...] [--output DIR] [--quiet]

      Loads every Ruby file under the given PATHs (default: lib/) and
      writes one .rbs file per Assistant::Service subclass found, under
      DIR (default: sig/).

      Existing .rbs files without the generator marker comment on their
      first line are left untouched.
    USAGE

    class << self
      def run(argv, stdout: $stdout, stderr: $stderr)
        new(argv, stdout:, stderr:).run
      end
    end

    def initialize(argv, stdout: $stdout, stderr: $stderr)
      @argv = argv
      @stdout = stdout
      @stderr = stderr
      @output_dir = DEFAULT_OUTPUT_DIR
      @quiet = false
      @paths = nil
    end

    # Returns an exit status (0 on success, non-zero on failure).
    def run
      parse_options!
      before = service_subclasses
      load_paths(@paths || DEFAULT_INPUT_PATHS)
      emit(service_subclasses - before)
      0
    rescue SystemExit => e
      e.status
    end

    private

    def emit(services)
      writer = Writer.new(output_dir: @output_dir, quiet: @quiet, stdout: @stdout, stderr: @stderr)
      services.sort_by(&:name).each do |service_class|
        writer.write(service_class, Renderer.render(service_class))
      end
    end

    def parse_options!
      OptionParser.new { |opts| configure_parser(opts) }.then { |p| @paths = p.parse(@argv) }
    end

    def configure_parser(opts)
      opts.banner = USAGE
      opts.on('-o', '--output DIR', "Output directory (default: #{DEFAULT_OUTPUT_DIR})") { |dir| @output_dir = dir }
      opts.on('-q', '--quiet', 'Suppress non-error output') { @quiet = true }
      opts.on('-h', '--help', 'Show this message') do
        @stdout.puts opts
        raise SystemExit, 0
      end
    end

    def load_paths(paths)
      paths.each do |path|
        if File.directory?(path)
          Dir.glob(File.join(path, '**/*.rb')).each { |file| safe_require(file) }
        elsif File.file?(path)
          safe_require(path)
        else
          @stderr.puts "[warn]      no such file or directory: #{path}"
        end
      end
    end

    def safe_require(path)
      require File.expand_path(path)
    rescue LoadError, StandardError => e
      @stderr.puts "[warn]      failed to load #{path}: #{e.class}: #{e.message}"
    end

    # Snapshot of every loaded Service subclass. Used to diff before /
    # after `load_paths` so we only emit signatures for classes whose
    # source files we were actually asked to scan -- this keeps a
    # long-running process (or a test suite) from re-emitting sigs for
    # every Service subclass it has ever seen.
    def service_subclasses
      ObjectSpace.each_object(Class).select { |klass| klass < Assistant::Service && klass.name }
    end
  end
end
