# frozen_string_literal: true

# Per-class RBS generator for `Assistant::Service` subclasses. The
# generic RBS shipped in `lib/assistant/service.rbs` cannot describe the
# per-input getter / predicate methods produced by the
# `Assistant::InputBuilder` DSL because their names and return types are
# only known at class-definition time. Users with Steep run this
# generator over their service files to obtain accurate signatures for
# their own subclasses.
#
# The generator is intentionally **not** loaded by `require 'assistant'`
# -- it is a developer-time tool. The shipped `exe/assistant-rbs`
# binary requires it explicitly.
#
# Marked Experimental in `docs/v1/01-api-surface.md` so the output
# format may evolve within 1.x.
#
# See `docs/v1/02-features.md` (M11) for the contract.
module Assistant::RbsGenerator
  MARKER = '# Generated by assistant-rbs; do not edit.'
  DEFAULT_OUTPUT_DIR = 'sig'
  DEFAULT_INPUT_PATHS = ['lib'].freeze
end

require 'assistant/rbs_generator/cli'
require 'assistant/rbs_generator/renderer'
require 'assistant/rbs_generator/writer'
