---
version: 2.1 # Use 2.1 to enable using orbs and other features.

commands:
  install_ruby_deps:
    steps:
      - checkout
      - ruby/install-deps:
            key: gems-v1

orbs:
  ruby: circleci/ruby@2.1.0
executors:
  ruby-executor:
    working_directory: ~/assistant
    docker:
      - image: cimg/base:stable
jobs:
  build-ruby:
    executor: ruby-executor
    parameters:
        ruby-version:
            type: string
    steps:
      - ruby/install:
          version: << parameters.ruby-version >>
      - install_ruby_deps
  ruby-unit-test:
    executor: ruby-executor
    steps:
      - install_ruby_deps
      - run:
          name: Run Unit Tests
          command: bundle exec rspec
  rubocop-check:
    executor: ruby-executor
    steps:
      - install_ruby_deps
      - ruby/rubocop-check

workflows:
  build-ruby-3-0:
    jobs:
      - build-ruby:
          ruby-version: 3.0.6
      - ruby-unit-test:
          requires:
            - build-ruby
      - rubocop-check:
          requires:
            - build-ruby
  build-ruby-3-1:
    jobs:
      - build-ruby:
          ruby-version: 3.1.4
      - ruby-unit-test:
          requires:
            - build-ruby
      - rubocop-check:
          requires:
            - build-ruby
  build-ruby-3-2:
    jobs:
      - build-ruby:
          ruby-version: 3.2.2
      - ruby-unit-test:
          requires:
            - build-ruby
      - rubocop-check:
          requires:
            - build-ruby
