---
version: 2.1 # Use 2.1 to enable using orbs and other features.

commands:
  install_ruby_deps:
    steps:
      - checkout
      - ruby/install-deps:
            key: gems-v1

orbs:
  ruby: circleci/ruby@2.0.0
executors:
  ruby-executor:
    working_directory: ~/assistant
    docker:
      - image: cimg/ruby:2.7.6
jobs:
  build-ruby:
    executor: ruby-executor
    steps:
      - install_ruby_deps
  ruby-unit-test:
    executor: ruby-executor
    steps:
      - install_ruby_deps
      - run:
          name: Run Unit Tests
          command: bundle exec rspec
  rubocop-check:
    executor: ruby-executor
    steps:
      - install_ruby_deps
      - ruby/rubocop-check

workflows:
  build_check_and_test:
    jobs:
      - build-ruby
      - ruby-unit-test:
          requires:
            - build-ruby
      - rubocop-check:
          requires:
            - build-ruby
