# frozen_string_literal: true

require 'assistant'

# Example service used to verify that signatures generated by
# `exe/assistant-rbs` (see docs/v1/02-features.md M11) are accepted by
# Steep. Kept intentionally small: one single-type input, one multi-type
# input, one allow_nil input -- covering every branch of the generator.
#
# The matching .rbs lives at `sig/examples/greeter.rbs` and is
# regenerated by running:
#
#   bundle exec exe/assistant-rbs examples --output sig
module Examples
  # Sample Service used to verify generator output type-checks.
  class Greeter < Assistant::Service
    input :name, type: String, required: true
    input :age, type: [Integer, Float]
    input :nickname, type: String, allow_nil: true

    def execute
      "hi #{name}"
    end
  end
end
