# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'
      - name: Setup project
        run: bundle install
      - name: Run test
        run: bundle exec rake all_specs
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: RuboCop Linter Action
        # You may pin to the exact commit or the version.
        # uses: andrewmcodes-archive/rubocop-linter-action@c9de2ff0e58217d3aa9167324b9dabdd2c6eefbe
        uses: andrewmcodes-archive/rubocop-linter-action@v3.3.0
