# frozen_string_literal: true

require_relative '../test_helper'
require 'assistant/rbs_generator'
require 'fileutils'
require 'tmpdir'

module Assistant
  class RbsGeneratorTest < Minitest::Test
    # --- Renderer ---------------------------------------------------------

    def test_renderer_emits_marker_class_header_and_getter_predicate_pairs
      service = define_service do
        input name: :name, type: String
        input name: :amount, type: Integer
      end

      expected = <<~RBS
        # Generated by assistant-rbs; do not edit.

        class #{service.name} < Assistant::Service

          def name: () -> String
          def name?: () -> bool
          def amount: () -> Integer
          def amount?: () -> bool

        end
      RBS

      assert_equal expected, RbsGenerator::Renderer.render(service)
    end

    def test_renderer_unions_multi_type_inputs_inside_parens
      service = define_service do
        input name: :amount, type: [Integer, Float]
      end

      assert_includes RbsGenerator::Renderer.render(service), 'def amount: () -> (Integer | Float)'
    end

    def test_renderer_appends_question_mark_for_allow_nil_inputs
      service = define_service do
        input name: :note, type: String, allow_nil: true
        input name: :score, type: [Integer, Float], allow_nil: true
      end

      output = RbsGenerator::Renderer.render(service)

      assert_includes output, 'def note: () -> String?'
      assert_includes output, 'def score: () -> (Integer | Float)?'
    end

    def test_renderer_handles_services_with_no_inputs
      service = define_service { nil }

      expected = <<~RBS
        # Generated by assistant-rbs; do not edit.

        class #{service.name} < Assistant::Service
        end
      RBS

      assert_equal expected, RbsGenerator::Renderer.render(service)
    end

    def test_renderer_raises_when_input_type_is_not_a_class
      service = Class.new(Assistant::Service) do
        def self.name = 'BadType'
      end
      # Bypass the DSL guard so we can verify the renderer's own check.
      service.send(:register_input_definition, name: :foo, type: 'String', options: {})

      assert_raises(RuntimeError) { RbsGenerator::Renderer.render(service) }
    end

    # --- Writer -----------------------------------------------------------

    def test_writer_creates_nested_paths_from_double_colon_class_names
      service = define_nested_service

      Dir.mktmpdir do |dir|
        writer = RbsGenerator::Writer.new(output_dir: dir, quiet: true)
        writer.write(service, RbsGenerator::Renderer.render(service))

        contents = File.read(File.join(dir, 'rbs_gen_acme', 'billing', 'charge.rbs'))

        assert_includes contents, 'module RbsGenAcme'
        assert_includes contents, '  module Billing'
        assert_includes contents, '    class Charge < Assistant::Service'
      end
    end

    def test_writer_is_idempotent_when_contents_match
      service = define_service { input name: :name, type: String }
      contents = RbsGenerator::Renderer.render(service)

      Dir.mktmpdir do |dir|
        writer = RbsGenerator::Writer.new(output_dir: dir, quiet: true)

        assert_equal :written, writer.write(service, contents)
        assert_equal :unchanged, writer.write(service, contents)
      end
    end

    def test_writer_refuses_to_overwrite_files_without_the_marker
      service = define_service { input name: :name, type: String }

      Dir.mktmpdir do |dir|
        target = seed_handwritten_rbs(dir, service)
        original = File.read(target)
        stderr = StringIO.new
        writer = RbsGenerator::Writer.new(output_dir: dir, quiet: true, stderr: stderr)

        result = writer.write(service, RbsGenerator::Renderer.render(service))

        assert_equal :skipped, result
        assert_equal original, File.read(target)
        assert_match(/no generator marker/, stderr.string)
      end
    end

    # --- Cli --------------------------------------------------------------

    def test_cli_loads_input_paths_and_writes_one_rbs_per_service
      Dir.mktmpdir do |dir|
        write_fixture_service(dir, 'cli_alpha_service.rb', 'CliAlphaService', <<~RUBY)
          input name: :name, type: String
        RUBY
        write_fixture_service(dir, 'nested/cli_beta_service.rb', 'CliBetaService', <<~RUBY)
          input name: :amount, type: [Integer, Float]
        RUBY

        sig_dir = File.join(dir, 'sig')
        cli = RbsGenerator::Cli.new([dir, '--output', sig_dir, '--quiet'])

        assert_equal 0, cli.run
        assert_path_exists File.join(sig_dir, 'cli_alpha_service.rbs')
        assert_path_exists File.join(sig_dir, 'cli_beta_service.rbs')
        assert_includes File.read(File.join(sig_dir, 'cli_beta_service.rbs')), 'def amount: () -> (Integer | Float)'
      end
    end

    def test_cli_help_returns_zero_and_writes_usage
      stdout = StringIO.new
      stderr = StringIO.new

      assert_equal 0, RbsGenerator::Cli.run(['--help'], stdout: stdout, stderr: stderr)
      assert_match(/Usage: assistant-rbs/, stdout.string)
    end

    def test_cli_warns_on_missing_path_but_still_succeeds
      stderr = StringIO.new
      Dir.mktmpdir do |dir|
        cli = RbsGenerator::Cli.new(['/no/such/path/here', '--output', dir, '--quiet'], stderr: stderr)

        assert_equal 0, cli.run
        assert_match(%r{no such file or directory: /no/such/path/here}, stderr.string)
      end
    end

    private

    def define_service(&block)
      const_name = "RbsGenTest#{self.class.next_counter}Service"
      klass = Class.new(Assistant::Service)
      Object.const_set(const_name, klass)
      klass.class_eval(&block) if block
      klass
    end

    def define_nested_service
      Object.const_set(:RbsGenAcme, Module.new) unless defined?(::RbsGenAcme)
      RbsGenAcme.const_set(:Billing, Module.new) unless RbsGenAcme.const_defined?(:Billing, false)
      return RbsGenAcme::Billing::Charge if RbsGenAcme::Billing.const_defined?(:Charge, false)

      svc = Class.new(Assistant::Service) { input name: :amount, type: Integer }
      RbsGenAcme::Billing.const_set(:Charge, svc)
      svc
    end

    def seed_handwritten_rbs(dir, service)
      writer = RbsGenerator::Writer.new(output_dir: dir, quiet: true)
      target = writer.send(:path_for, service)
      FileUtils.mkdir_p(File.dirname(target))
      File.write(target, "# user wrote this; do not touch\nclass #{service.name}; end\n")
      target
    end

    def write_fixture_service(root, relative, const_name, body)
      target = File.join(root, relative)
      FileUtils.mkdir_p(File.dirname(target))
      File.write(target, <<~RUBY)
        # frozen_string_literal: true
        require 'assistant'

        class #{const_name} < Assistant::Service
          #{body.strip}
        end
      RUBY
      target
    end

    # Counter used so each call to `define_service` minted a uniquely
    # named global constant; needed because the renderer relies on
    # `klass.name`, which is `nil` for anonymous classes.
    @counter = 0

    class << self
      def next_counter
        @counter ||= 0
        @counter += 1
      end
    end
  end
end
